# Site settings
locale: "zh-CN"
title: "THE ALIEN"
author: "Neil Yin"
description: "&quot;The older I grow, the more of an alien I find myself in the world; I cannot get used to it, cannot believe that it is real. I think I must have been made to live on some other Star. Or perhaps I am subject to hallucinations and hear voices; perhaps what I seem to see is delusion and doesn't happen; perhaps people don't really say the things I think I hear them saying.&quot;&nbsp;&nbsp;(by Logan Pearsall Smith)"
keywords: "Software Engineering, Management, Philosophy, THE ALIEN, Neil Yin, sanglin, 殷亮, 桑林咨询"
biography: "Neil Yin<br>IT作家·咨询顾问"
colophon: "© 2019 by Neil Yin.<br>This site is hosted at <a href='https://pages.github.com/'>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a>."

baseurl: ""
url: "http://neilyinliang.github.io"

twitter_username: 
github_username: neilyinliang
email: neilyin@msn.com
linkedin_username: 
facebook_username: 
google-analytics: 

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
